### ISSUE TITLE
bug - trade modal crashes when selecting assets

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1246]
[3:11 PM] wesley graves: when the cosmos flag is on, clicking on an input or output asset in the trade modal crashes the site to a white page

**Comment by cjthompson** [comment]
I agree that it shouldn't crash but it's not clear what the expected behavior should be since we don't support trading of any cosmos assets.

This is one reason why, I feel, we need to move away from a single all-in-one trade modal.

Regardless, what's the expected behavior? How do we filter out assets that we can't trade?

**Comment by 0xdef1cafe** [comment]
fixed in prod 3/22
