### ISSUE TITLE
Trade widget wrong error message initial state

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#1287]
### Overview

We made some changes yesterday that have broken a cypress test related to the trade widget state on the dashboard.

The initial label on the button should be `Loading...` or similar, not `Not enough ETH to cover gas`

### References and additional details

You can run `yarn test:cypress:headless` locally to run the Cypress tests.

```
  Running:  dashboard_spec.ts                                                               (1 of 3)


  The Dashboard
    ✓ nav bar works (37619ms)
    ✓ displays the expected account rows (191ms)
    1) supports trades
    - supports send transaction setup
    - supports receive transaction setup


  2 passing (1m)
  2 pending
  1 failing

  1) The Dashboard
       supports trades:

      Timed out retrying after 25000ms
      + expected - actual

      -'Loading...Insufficient Funds'
      +'Not enough ETH to cover gas'      
```

### Acceptance Criteria

* Figure out how to make the initial button state in the trade widget `Loading...`
* Update the cypress tests accordingly

### Need By Date

3/25

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Sponsor / Stakeholder

@0xdef1cafe

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
I think the issue is actually that in `getTranslationKey` we are early exiting on condition `isValid && !hasValidTradeBalance`, impliying that `hasValidTradeBalance` is `false` when it shouldn't be.

Cypress waits for the correct value to resolve (in this case, `Not enough ETH to cover gas`), so I don't think it's related to the inital value.

**Comment by 0xApotheosis** [comment]
I think the value that Cypress resolves should really be `Insufficient Funds`, which is what the (failing) tests were showing when this issue was created.

Interestingly, updating the axios package to `0.26.1` appears to have "fixed" this logic (`getTranslationKey` started returning a value that made more sense_
