### ISSUE TITLE
Transactions can't be initiated until charts fully load

### ISSUE THREAD

**Issue by willyogo** [shapeshift/web#1934]
### Overview

After i connect my wallet or refresh, it takes several minutes for the app to fully load my balance from all my tx history (willywonka.eth). if I attempt initiate a trade tx before the the app has fully loaded, the approve/confirm button will spin until everything is fully loaded, and as soon as charts and balance load, the wallet will prompt me to confirm the tx. if I attempt to send, the confirm button won't activate until everything is loaded.

### References and additional details

steps to repro:
1. have a wallet with a lot of tokens and/or tx history (you can use willywonka.eth for testing)
2. before balance chart fully loads, attempt to initiate a tx in the app (if you try to trade, app will let you click confirm; if you try to send, confirm button won't even activate)

expected result:
wallet prompts confirmation immediately after initiating tx in the app

actual result:
wallet does not prompt confirmation until charts are fully loaded

### Acceptance Criteria

AC:
1. Users can create a transaction even before the app is fully loaded
AND/OR
2. Charts load in <10 seconds. 

Either of these AC would improve the UX. If chart data loads in a reasonable time (ie. <10 seconds), then #1 is less important. If we only do AC #1 for this issue, let's make a separate issue for AC #2.

On #2, implementation is entirely up to engineering, but i have some questions:
1. are we caching users' tx history? it seems like the app is re-downloading my full tx history on every refresh
2. if we show the 24 hour chart by default, don't we only need to download the users current balances, first 24 hours of a users' tx history, and price data to fully load the 24 hour chart? it seems the app is waiting to download my complete tx history before it will show the 24 hour chart

### Screenshots/Mockups

![image](https://user-images.githubusercontent.com/26232238/171900913-685905b6-792f-4f48-91a7-7998fbfb80e7.png)

### Estimated effort

needs engineering

**Comment by 0xdef1cafe** [comment]
considered blocked until @kaladinlight finishes removing ingester + restful tx history, websockets caused a lot of perf issues in the client on app load which is mitigated with new architecture

**Comment by 0xdef1cafe** [comment]
@willyogo friendly ping on this one - i tested with one of your testing wallets, page loaded in under 10s and the trade widget wasn't blocked during that period.

i'm inclined to close this one for a few reasons

* we don't have users complaining about this
* @kaladinlight has historical tx history loading restfully now, rather than over websocket, so we're faster both over the network to load, and page performance wise (batched renders of txs). 
* @elmutt @0xApotheosis @DaoDev44 et al have made a lot of simplifications to swapper recently, and this may no longer be relevant

@willyogo if you could give this a quick smoke test and let us know if we're good to close. we could investigate this - but the likely fix would be app level rendering/selector performance issues, rather than anything specifically to do with tx history or swapper

**Comment by willyogo** [comment]
ty for the ping! just tested and metamask prompts instantly, this looks fixed. thank you!
