### ISSUE TITLE
Cypress cross-origin regression 

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#1941]
### Overview

https://github.com/shapeshift/web/pull/1898 caused a regress preventing Cypress from running locally.

### References and additional details

`cy.visit` errors with the below cross-origin error:

<img width="794" alt="Screen_Shot_2022-06-05_at_5 54 32_am" src="https://user-images.githubusercontent.com/97164662/172024595-247efbbf-ada2-4c28-bfc6-500b51c0f784.png">

### Acceptance Criteria

Reproduce by locally running `yarn test:cypress`, which will launch Cypress in headed mode, and running all tests.

**Comment by mrnerdhair** [comment]
As of #1898 you have to use `yarn dev:cypress` (instead of `yarn dev` or `yarn dev:silent`) when running cypress tests so that `CYPRESS_RELAXED_SECURITY` is used. (I made that change to the GH action, but I suppose it wouldn't hurt to drop `dev:cypress` and just put that option in the normal `dev` and `dev:silent` commands, if that would be helpful from a workflow perspective.)
