### ISSUE TITLE
Description of FOX in the header on the new FOX page is not translatable

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#2052]
### Overview

The new FOX page includes a description of the token in the header, right under the title. I've found that it's not defined as a translatable string currently, it's a const in the code and doesn't pass through the translation function: https://github.com/shapeshift/web/blob/27798dfc62f3f53d037c285ddd60cc91a478cad9/src/plugins/foxPage/foxPage.tsx#L72

Reported by Firebomb

### References and additional details

https://cdn.discordapp.com/attachments/898694346705080350/986719969351958528/unknown.png

### Acceptance Criteria

Header description needs to be able to be translatable

**Comment by DiggyDiggy2** [comment]
hey @gomesalexandre, who should I assign to this one?

**Comment by gomesalexandre** [comment]
> hey @gomesalexandre, who should I assign to this one?

You can keep me assigned to it! Just to clarify before we start work on it, this is just a technical change and won't bring translations for the Fox Page unless provided by product, does it sound good to you?

**Comment by firebomb1** [comment]
> this is just a technical change and won't bring translations for the Fox Page unless provided by product

The Globalization team will gladly translate it when the string is available 👍 (which is why I've reported it as the French translator)

Aside from this specific FOX page, in which the description is in the "web" repo code, there is a broader problem with asset descriptions being displayed only in English in the app and not being translatable/translated.

From what I've seen, fixing this would affect "lib" (where other asset descriptions are retrieved) and "web" (where the user language is known). Should this be fixed while we're at it?

The good news is the CoinGecko API endpoint used in "lib" to get asset descriptions already returns translated descriptions when available (e.g. [for Ethereum]( https://api.coingecko.com/api/v3/coins/ethereum), see the "description" key), we just [only use English ones currently](https://github.com/shapeshift/lib/blob/94f74495b8d3b082517c10c60288f8fa1e411daf/packages/asset-service/src/service/AssetService.ts#L57). Falling back to English descriptions when a translation is not available would be good enough I think.

The kinda bad news is we also have ["overridden" descriptions](https://github.com/shapeshift/lib/blob/94f74495b8d3b082517c10c60288f8fa1e411daf/packages/asset-service/src/service/descriptions.json) that are located in "lib" that are currently only in English... so we should provide a way to get these strings translated if possible.

**Comment by NeOMakinG** [comment]
> "overridden" descriptions

I guess the override of the Fox description should operate only on fox page, not on the asset page and whatever.

If we need to override the description of that asset everywhere, let's override it in lib and then find a solution to provide i18n strings from that lib override

**Comment by gomesalexandre** [comment]
> > "overridden" descriptions
> 
> I guess the override of the Fox description should operate only on fox page, not on the asset page?
> 
> If we need to override the description everywhere, let's override it in lib and then find a solution to provide i18n strings from lib

Correct @NeOMakinG those are two different problems. Within the scope of the Fox Page, moving the current constant to translations will make it translatable and will close that issue.

WRT the descriptions from Coingecko coming back as English only, there is a bit more work involved that will span across lib + updating web consumption of descriptions. We should definitely spike the best way to achieve it in a different issue.

Thanks a lot for spiking this @firebomb1

**Comment by gomesalexandre** [comment]
@firebomb1 Here's the lib issue for this: https://github.com/shapeshift/lib/issues/836

**Comment by gomesalexandre** [comment]
Fixed by https://github.com/shapeshift/web/pull/2098

**Comment by gomesalexandre** [comment]
@firebomb1 All ready for globalization team to translate this! Let me know if there's anything you guys need on how to contribute them

**Comment by gomesalexandre** [comment]
Reopening as this will still need an accompanying web PR fox the original issue
