### ISSUE TITLE
1M price charts flat lining for the last part of the month for ETH, ERC-20 and BTC assets

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2199]
### Overview

When looking at the 1M price chart for assets, either from the asset or account page, the current price is showing as $0.00.

### References and additional details

1) Log into app.shapeshift.com
2) Connect to any wallet
3) Select any asset and check the price on the 1M chart
4) Notice it says the current price for assets is $0.00
![image](https://user-images.githubusercontent.com/100157997/180120371-000e1027-b098-4b4a-96bc-f2696809664a.png)
Noticed from today 7/20/22. Today's release  was 1.44.0 - https://github.com/shapeshift/web/pull/2196 .
Noticing it on all wallets - zero balance for assets in 1M graph

### Acceptance Criteria

1M chart should reflect current price of asset. 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xdef1cafe** [comment]
ok - this is a legitimate issue, and most of engineering would not have seen this on the US timezone.

this is only affecting people on timezones with a positive GMT offset - sydney (+10) and manila (+8) can repro this

it affects charts on the 1 month or shorter timeframe.

https://github.com/shapeshift/web/blob/develop/src/hooks/useBalanceChartData/useBalanceChartData.ts#L88

this would have been caused by me some weeks/months ago when the initial portion of multicurrency support went in - we don't have forex rates into the "future" - we'll have to extrapolate from the previous days rates

**Comment by 0xdef1cafe** [comment]
fix in lib https://github.com/shapeshift/lib/pull/918
