### ISSUE TITLE
Keplr Error when connecting

### ISSUE THREAD

**Issue by tshifty** [shapeshift/web#2267]
### Overview

Currently, when connecting your kelpr wallet you get two error toasts that pop up (pops up on clicking receive address as well) Attached are the errors that you get in development tools.

Looks like it is looking for an eth address and erroring out because its an atom only wallet imo.

### References and additional details

![ethaddress?](https://user-images.githubusercontent.com/94189400/181615667-f7cfc64e-16d9-4efa-82b1-eb311cc1bece.jpg)

### Acceptance Criteria

Toast error should not prompt as it seems there is nothing wrong with using kelpr with app.shapeshift.com

**Comment by gomesalexandre** [comment]
This is caused by the Osmosis swapper which caused a "regression" (no functional regression per se, but a cheeky error popping up).

We are attempting to use FOX (ETH/FOX pair) as a buyAsset in `getFirstReceiveAddress` which is wrong for a non-Ethereum-supporting wallet:
https://github.com/shapeshift/web/blob/f7f4e955a4410e8d7065c3f9fa071bf00f97858e/src/components/Trade/hooks/useSwapper/useSwapper.ts#L326

IMO we should never get to this branch with such pair in the first place, and we should have default pairs in place so that by the time this method is called, we already have the right pair setup, see EVM chains default pairs implementation:
https://github.com/shapeshift/web/pull/2223
