### ISSUE TITLE
Switching Chains - handle smoothly for the user

### ISSUE THREAD

**Issue by DiggyDiggy2** [shapeshift/web#2335]
### Overview

When a user switching chains, for example from Avalanche to Ethereum, we should just reload the app without kicking the user to the splash screen.

### References and additional details

1. connect a wallet with both avalanche and eth support on
2. switch from one to the other
3. you will get kicked out to the splash screen. This is not the desired behavior.

### Acceptance Criteria

If a user switches chains, it should just switching without disconnecting their wallet.

**Comment by gomesalexandre** [comment]
Didn't notice this behavior while running the app with the local dev server, but it is happening on production, will need to investigate some more to be able to repro locally.

**Comment by gomesalexandre** [comment]
Caused by https://github.com/shapeshift/web/blob/55a12d56f532673a7ab6be9c454224e6b5873024/src/Routes/Routes.tsx#L31
Switching chains effectively loses the wallet (`state.walletInfo?.deviceId`) info.

We will need either:
- a silent wallet reconnection of sorts before actually disconnecting
- improve our `useWallet()` logic not to lose wallet info
