### ISSUE TITLE
The APR for ETH-FOX liquidity pool different in the Defi and Fox Opportunity page compared with the Fox Token Benefits page.

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2379]
### Overview

When looking at the APR for ETH-FOX liquidity pool in app.shapeshift, it is slightly different to the value given on the FOX Token Benefit page (fox.shapeshift.com)

### References and additional details

1) Log into app.shapeshift.com and connect to wallet of choice.
2) Navigate to the FOX Opportunity page and notice under the Farming section, the APY for ETH-FOX UNI V4 Farm is 44.04%. (Same value displayed on the Defi Earm page)
3) Select the 'Get Started' option
4) Notice the APR on the FOX Token Benefit Page states the APR as 44.7685%
![image](https://user-images.githubusercontent.com/100157997/183792414-c2f1e1cf-a147-47c9-a589-ba5ed5c40aaf.png)
![image](https://user-images.githubusercontent.com/100157997/183792436-9e060af7-ce55-4ac5-9e0b-1d9f7d81b1d9.png)

### Acceptance Criteria

APR should be consistent across platforms/pages

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
The foxfarm repo currently does farming rewards APY + LP fees APY to render the total APY, see:

https://github.com/shapeshift/foxfarm/commit/5bd9220#diff-29b7d3d412a9d1062aaa5bca55ead16a808dc5a47423d78727ac8469bc199239R197

Whereas web only uses the farming APY to display the farming APY

Discussed this one out with @0xean and this was by design, to show the full APY that you'll get from the LP token itself (fees yield) + the one from farming your LP (rewards yield).

Will need to sync by @shapeshift/product to make the UX of this match the one of the foxfarm repo - meaning we might also want to show the farming APR first, since it is otherwise collapsed.
