### ISSUE TITLE
Unhandled `SellAmountDoesNotCoverFee` response from CowSwap

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#2397]
### Overview

When attempting to use CowSwap to sell an amount of an asset that is less than the CowSwap minimum we currently show an error popup: `Something went wrong. An error occurred getting a quote for your trade.`.

### References and additional details

This occurs when the request to `https://api.cow.fi/mainnet/api/v1/quote/` returns a response payload similar to the following:

```json
{
    "errorType": "SellAmountDoesNotCoverFee",
    "description": "The sell amount for the sell order is lower than the fee.",
    "data": {
        "fee_amount": "0x2be89a7500ca68000"
    }
}
```

I tested using `VBNT` to `FOX`.

Noting that this does seem to be handled for `USDC` to `FOX`:

<img width="585" alt="Screen Shot 2022-08-11 at 9 08 08 am" src="https://user-images.githubusercontent.com/97164662/184038226-c26e637c-33e1-40e8-baa0-a99ac6e46940.png">

### Acceptance Criteria

Ideally, we'd be able to still get a quote for the user when the amount is too low, but not let them proceed with the transaction by providing appropriate errors/UI to the user.

### Screenshots/Mockups

<img width="450" alt="Screen Shot 2022-08-11 at 9 00 33 am" src="https://user-images.githubusercontent.com/97164662/184037572-a7a860c7-8609-4ef5-87b1-fc33410ad493.png">

**Comment by 0xApotheosis** [comment]
@gomesalexandre FYI sir.

**Comment by 0xApotheosis** [comment]
A related, but separate issue is that the fiat amount of the sell asset does not update on failed quote response.

These should be decoupled.

**Comment by willyogo** [comment]
FYI, CowSwap handles this by disabling the "Swap" button and displaying "Fees exceed from amount" until user inputs a valid amount.

I think it's fine if we can't display the rate after a user has input an amount, but agree that not letting them proceed with the TX and showing the error in the trade modal rather than a toast message would be an improvement.

UI improvements aside, I think we are handling the error correctly if a user inputs an amount below the min (like in the USDC -> FOX example you posted). I would investigate the amount we use to request a quote before a user has input any amount to see if this is also at least $20.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/26232238/184038383-89cfa86f-5cc2-4b59-a25d-3f811ba8f393.png">

**Comment by gomesalexandre** [comment]
> Ideally, we'd be able to still get a quote for the user when the amount is too low, but not let them proceed with the transaction by providing appropriate errors/UI to the user.

In theory, we won't be able to get a quote if the amount is too low, since Cow.fi returns us an error response in this case.

There could be ways for us to still get a quote, e.g using 0x API as a fallback, using a higher value and using the returned quote prorated, but both options come with implications either in complexity, accuracy, or both and IMO do not belong in this issue @0xApotheosis

Authored https://github.com/shapeshift/lib/pull/965 and https://github.com/shapeshift/web/pull/2403 as a first step - this is still emitting a toast, and there will be a follow-up web PR to improve the UX and close this issue (quite a bit more logic will be needed), but for now, this will at least handle the error.

@shapeshift/product @willyogo do we agree with this flow/copy as an intermediary step? 🙏🏽

**Comment by 0xdef1cafe** [comment]
addressed by above PRs
