### ISSUE TITLE
Trade Widget and Page on Keplr not loading correctly with Thorswap flag on

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#2961]
### Overview

When logging into Keplr wallet, the trade widget isnt loading and gives an error message of "Sell asset not supported by wallet".
The Trade page also displays the same error. After doing a refresh on the Dashboard, the trade widget loads and gives the correct error "ETH not supported by wallet". After navigating to the trade page to see if it loads, which is does not, and back to dashboard, it reverts to the original "Sell asset not supported by wallet" error message

### References and additional details

1) Log into release.shapeshift.com and connect to Keplr wallet. (For testing the Thorswap flag is enabled by default. Release: https://github.com/shapeshift/web/pull/2954)
2) Notice the trade widget does not load and gives an error message of "Sell asset not supported by wallet".
3) Navigate to the Trade Page and notice the same thing.
4) Return to Dashboard and refresh. 
5) Notice the Trade widget load correctly.
6) Switch to the Trade page and notice the original error still occurring.
7) Navigate once again to Dashboard and notice the trade widget doesn't load:
![image](https://user-images.githubusercontent.com/100157997/193726157-19302286-6fbb-4887-b512-30c44fc6eb01.png)
After refresh the widget loads like this:
![image](https://user-images.githubusercontent.com/100157997/193726173-ab1f44f0-ebd2-46b5-9f22-c51365c09341.png)

### Acceptance Criteria

Trade widget and page should have the correct message of ETH not supported by wallet for Keplr wallet

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
With `Osmosis` on, I did notice the "Sell asset not supported by wallet" , however, this fixed itself after a few seconds once portfolio data is loaded.
With `Osmosis` off, I was able to reproduce the bug.

The reason why we didn't spot this in develop is because Osmosis gets enabled for `.env.develop` only, and is off for other envs. 

Without Osmosis on, and without the ability to select an address for tokens to be sent to, there is effectively no valid pair.

We do have some logic to default to the ETH/FOX pair, however, it is invalid in Keplr which doesn't support EVM chains:

https://github.com/shapeshift/web/blob/9c4e8040534a884fc8e10e09bf61cfb6f9ee5c12/src/components/Trade/hooks/useSwapper/utils.ts#L192-L195

Graceful ways to handle this would be either to consistently enable Osmosis, or to disable swapper for Keplr if the Osmosis flag is off, with a "No available pairs" or similar error.

**Comment by DiggyDiggy2** [comment]
Unfortunately, with Osmosis on (in develop and in prod) the swapper misbehaves. it doesn't allow numbers to be entered into the form fields. And I doubt that's something we want to fix right now. Please see attached mock up - we think an overlay like this will be best for now.

https://cdn.discordapp.com/attachments/867117399978934353/1026878059216900107/Screen_Shot_2022-10-04_at_10.26.44_AM.png

to make the blur: backdrop-filter: blur(20px)

**Comment by reallybeard** [comment]
Lets make a `OverlayMessage` component I have a feeling we may require this functionality somewhere else in the future.

```
<OverlayMessage title='Swapping for Keplr is coming soon' show={true}>
    <Trade />
</OverlayMessage>

```
