### ISSUE TITLE
Handle exact-amount approvals with no subsequent trade

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#3331]
### Overview

If "exact amount" is selected when starting a trade from an asset without a valid approved spend, and the approval goes through but no subsequent trade occurs, we end up in a bad state.

### References and additional details

`estimateGas` in `unchained` throws `500`, though we should probably make it return an error message and then handle that in the client.

### Acceptance Criteria

Error case is gracefully handled informing the user of the issue. 

Longer term we might want to allow the user to reset the approved amount to 0 and re-approve.

### Screenshots/Mockups

<img width="1076" alt="Screenshot 2022-11-15 at 7 05 50 pm" src="https://user-images.githubusercontent.com/97164662/201863663-4f9335fe-f495-478a-8e6b-ccbc7186685b.png">

**Comment by DiggyDiggy2** [comment]
@0xApotheosis is this still an issue?

**Comment by 0xApotheosis** [comment]
It would be @DiggyDiggy2, yes.

**Comment by gomesalexandre** [comment]
Confirmed this is still happening @0xean - see https://github.com/shapeshift/web/pull/5774#pullrequestreview-1770421213 where I manually set the allowance to 2 FOX instead of the 3 one we automagically send to MM for that approve Tx.

We're not crashing, but not handling things elegantly either, spinning forever instead. We should *not* be in a loading state anymore once an approval *Tx* has been succesful (or failed, for that matter).
 
 
<img width="618" alt="image" src="https://github.com/shapeshift/web/assets/17035424/fa2e29f9-ad43-4c53-96cf-0ff4ba59fe24">

We should *not* relying on the allowance being granted as a loading state, as users may be manually setting a wrong allowance. Instead, the `approve()` Tx should be used as a check - cc @woodenfurniture

**Comment by woodenfurniture** [comment]
after discussing this with gomes, the solution in multi-hop is to decouple tx pending state from approval being granted to proceed to the next step. Will add a message to the approval await so users are aware

**Comment by woodenfurniture** [comment]
Some additional details
https://github.com/shapeshift/web/pull/5774#discussion_r1419096422

And
```
...a more correct approach instead of block number and allowance checks as a source of truth, would be to rely on:

1. using waitForTransaction : https://wagmi.sh/core/actions/waitForTransaction. That will remove the need for block number checks, since this will wait until the Tx is confirmed
2. the transaction as a source of truth for loading states. We shouldn't care about whether the allowance is granted or not as a loading state. We obviously do want to listen to allowance being granted as way to automagically route to the next step, but we should never keep spinning once the approve() Tx has been confirmed
```

and
```
We should stop spinning on Tx complete, not on allowance granted
Basically decoupling the Tx completion and allowance:
- Tx loading/success state is the one that makes the spinner spin
- allowance granted is the one that makes us automagically go to the next step
Would avoid that edge case of granting less and then spinning forever, with no way to grant allowance again 
```
