### ISSUE TITLE
CowSwap EVM chains support

### ISSUE THREAD

**Issue by lmyslinski** [shapeshift/web#4552]
### Overview

CowSwap currently only supports Ethereum Mainnet-> Ethereum Mainnet swaps, we'd like to support all valid same-chain swaps for all supported assets on Shapeshift, that list currently includes:

- Optimism
- Polygon
- Avalanche
- Gnosis
- BNB

### References and additional details

Might be worth looking into https://github.com/shapeshift/web/issues/4497 within this effort

### Acceptance Criteria

* The users can swap same-chain assets for all evm chains

**Comment by gomesalexandre** [comment]
CoW only supports Ethereum mainnet (+Goerli as a testnet) and Gnosis, so only Gnosis will be able to be added as a supported chain.
Re: `all supported assets on Shapeshift`, native assets (ETH for Ethereum, and xDAI for Gnosis) will only be available as *buy* assets - that's due to the way CoW works, their UI supports native assets sell through a proxy (https://docs.cow.fi/smart-contracts/eth-flow-contract) but there's way too much complexity in this
