### ISSUE TITLE
LiFi unable to perform Max trades on OP 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#4561]
### Overview

When trying to perform a Max bridge of OP to ETH the bridge attempt returns an Optimism 400 error and the trade is not able to be performed. The user is not prompted with an error and the button to attempt again is clickable with no change in outcome.  

### References and additional details

<img width="611" alt="Screen Shot 2023-05-24 at 9 50 15 AM" src="https://github.com/shapeshift/web/assets/94998097/5330f9bf-8458-4eef-a3ca-f50098b0d27d">
Max OP bridge to ETH

<img width="552" alt="Screen Shot 2023-05-24 at 9 37 03 AM" src="https://github.com/shapeshift/web/assets/94998097/2242b904-fa10-4a09-a17d-ae651b0d4301">
400 Error

<img width="626" alt="Screen Shot 2023-05-24 at 9 50 32 AM" src="https://github.com/shapeshift/web/assets/94998097/80a9c0b6-8f89-4e32-9749-83a7f5319ac5">
message: "invalid transaction: insufficient funds for gas * price + value"

### Acceptance Criteria

LiFi handles Max calculations plus gas to be able to perform Max input bridges.  

### Screenshots/Mockups

See References

**Comment by MBMaria** [comment]
this happens with max sends of eth on optimism as well 
![image](https://github.com/shapeshift/web/assets/100157997/b94ca6e6-054f-4f42-96a2-3f8b4e2fa70d)
![image](https://github.com/shapeshift/web/assets/100157997/924f5e5f-43d0-461e-b549-34301bcd8598)

**Comment by woodenfurniture** [comment]
One of the remaining issues with max sends on lifi is that to determine the max send we do the following:
1. fetch quote using sell asset balance
2. use that quote to determine max possible sell amount - `maxSellAmount = balance - networkfee - protocolfee`
3. fetch a quote using that sell amount and return it to the UI

The issue is that with lifi the route can be totally different and the fees can be totally different, meaning the maximum sell amount is likely too high to too low. If the amount is too high, the trade wont go through due to insufficient balance.

We can reduce the likelihood of this scenario by telling lifi to fetch a quote for the same `tool` (i.e the bridge) that was used in the original quote.

See screenshot showing the estimated gas from metamask is higher than ours which prevents user confirming trade
![image](https://github.com/shapeshift/web/assets/125113430/41ae3b3d-f431-47ce-a44d-fd7ceb28c1b4)

**Comment by woodenfurniture** [comment]
no more max button -> closed.
