### ISSUE TITLE
Max BCH trade is a deadclick

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#4872]
### Overview

when trying to trade max BCH the preview trade button is a dead click

### References and additional details

1) log into app.shapeshift and connect to wallet of choice
2) Navigate to Trade page and enter a max BCH trade 
3) Note that you can select preview trade but it doesnt take you to the next step.
![image](https://github.com/shapeshift/web/assets/100157997/285ecc24-9bbf-460f-89d2-51bd3d76642a)

### Acceptance Criteria

should be able to trade max BCH

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by gomesalexandre** [comment]
Tried to bisect this one and it looks like this has been here for quite some time, as I can consistently repro this, and can't repro on other chains. Note, this not only happens on send maxes, but also while removing a few sats/decimal places, meaning our fee deduction is wrong.

While I initially thought of bringing the notion of `sendMax` to swapper as a holistic notion (i.e we would have a `sendMax` property that would then be passed to chain-adapters), this would only fix things for actual max sends, not amounts close to it.

It looks like the issue is our sats per byte for BCH currently sits at around 1000 sats, while it looks like the network expects ~1700 sats per bytes currently, effectively making the coinselect selection fail

<img width="394" alt="image" src="https://github.com/shapeshift/web/assets/17035424/fa0a1681-dfb0-453c-92ec-e9de8e26104d">

This is actually documented already, see

https://github.com/shapeshift/web/blob/20a5e102467e966fc658f11e56455853ac0232a2/src/lib/swapper/swappers/ThorchainSwapper/utils/txFeeHelpers/utxoTxFees/getUtxoTxFees.ts#L36-L40
