### ISSUE TITLE
Selecting an opportunity unsupported by wallet infinite spinner

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#5130]
### Overview

On the DeFi tab, when connected to a wallet that does not support an opportunity, we still show the opportunity, but when it's clicked we render an infinite spinner in a modal.

### References and additional details

E.g. select BTC Thorchain saver opportunity whilst connected to MetaMask:

<img width="820" alt="Screenshot 2023-08-22 at 11 06 39 am" src="https://github.com/shapeshift/web/assets/97164662/598cb3d7-e5c6-446d-bb19-1546b1c5cb58">

### Acceptance Criteria

Either don't show the opportunity, or have smarted UX to inform the user that they aren't using a compatible wallet.

One for @shapeshift/product @twblack88 @reallybeard to decide.

**Comment by twblack88** [comment]
Can we just grey out opportunities that aren't eligible?

**Comment by gomesalexandre** [comment]
I raised that one a long time ago with product and the product consensus back then was to show all opportunities for all wallets, the rationale being better discovery i.e you could then switch wallets to deposit into said opportunity.
@twblack88 greying out opportunities will be super easy if that's what we want, since an opportunity has a ChainId, and a wallet has non/supported ChainIds
