### ISSUE TITLE
ThorChain Saver modal for USDC on Avax doesn't update once tx has confirmed on blockchain 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5264]
### Overview

When depositing or withdrawing from the USDC on Avax vault, the modal does not update once the tx has confirmed on the blockchain

### References and additional details

1) log into app.shapeshift and connect to wallet of choice
2) Navigate to defi page and select usdc on avax
3) enter an amount to deposit/or withdraw and continue
4) broadcast the transaction and note that the modal keeps spinning even after the tx has confirmed on the blockchain 
![image](https://github.com/shapeshift/web/assets/100157997/54e89c7e-04b4-44aa-b0a0-1d5a44f95bf5)
![image](https://github.com/shapeshift/web/assets/100157997/8d5682d7-8cb8-4529-9e80-b1178a0e5d2e)

### Acceptance Criteria

Modal should update one tx has confirmed on blockchain

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by MBMaria** [comment]
Still experiencing this :(
The balance did update tho, just the modal that remained on 'Transaction Pending'
![image](https://github.com/shapeshift/web/assets/100157997/ebe46feb-d3a7-4203-b3fb-10ff5525503d)

**Comment by MBMaria** [comment]
Still getting this
![image](https://github.com/shapeshift/web/assets/100157997/c7be13cc-be7f-4156-8361-742646d03b4c)

**Comment by MBMaria** [comment]
so weird @gomesalexandre . the balance will update and the tx shows completed in activity but the modal just seems to remain on pending .?
![image](https://github.com/shapeshift/web/assets/100157997/6b1076fb-aa74-4b58-ae01-76d50b248ac0)

**Comment by gomesalexandre** [comment]
@MBMaria outbound completion checks should now be properly handled, including outbound delays, could you please check ? Unfortunately I'm out of testing funds to double check that one, but the approach we took in outbound checks was holistic so we should be good here🙏🏽 

Just to reemphasize what are the expectations here:

- Deposits will be fairly quick to be reflected as success, since no outbound Tx is occurring
- Withdraws may or may not take a very long time to go to confirmed state depending on current outbound delays - that *is* expected, and indeed, balance may update a minute or a few before the DeFi modals says success, in case of very long outbounds (e.g 1+ hours)
