### ISSUE TITLE
Cannot transact with 1Inch wallet connected via Wallet Connect

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#5421]
### Overview

1inch can connect to wallet connect as a wallet but when you try to do a tx, shapeshift app gives an error before getting the chance to sign in the 1inch wallet. 

### References and additional details

1) Log into app.shapeshift.com and select Wallet Connect
2) Connect 1inch wallet to Wallet Connect
3) Try to do a send or trade and an error comes up straight away 
send:
![image](https://github.com/shapeshift/web/assets/100157997/df21bd14-68ed-4abf-aac3-5ab42f2fd4c4)
![image](https://github.com/shapeshift/web/assets/100157997/f5d64ecb-f5e8-462c-9d8b-ab25c7ca9a70)
trade:
![image](https://github.com/shapeshift/web/assets/100157997/fe41cb19-fdba-4fdc-9c90-7f5aed1bc36d)
![image](https://github.com/shapeshift/web/assets/100157997/df323b6b-036a-4d44-a9a6-f927163b40d1)

### Acceptance Criteria

Should be able to use 1inch connected via WC

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
We've investigated this issue, and have found the following:

All mainnet trades are working when connected via 1inch android app, but not iOS app
Non-mainnet trades fail.

Occasionally seeing an issue where 1inch wallet is able to scan a barcode but cannot connect to shapeshift, reloading 1inch mobile app resolves the issue.

After connecting 1inch wallet to shapeshift, the mobile app shows 0 conections in wallet options next to walletconnect until you close and re-open the wallet options.

The request to trade on avalanche is pushing an ethereum request to 1inch wallet

### 1inch wallet via walletconnect
ERC20 allowance approvals on mainnet - android ✅, iOS ❌
ERC20 -> ERC20 trade on mainnet - android ✅, iOS ❌
ETH -> ERC20 trade on mainnet - android ✅, iOS ❌
ERC20 -> ETH trade on mainnet - android ✅, iOS ❌

ERC20 allowance approvals on avalanche - android ❌ results in approval TX being sent on mainnet instead of avalanche chain https://etherscan.io/tx/0x060c033ac8e8ebd416125e0ff7b20c4b1fa5d6c711885b72df9712d0e1ac73f7
ERC20 -> ERC20 trade on avalanche - android ❌ `INTERNAL_ERROR: IntrinsicGas`
AVAX -> ERC20 trade on avalanche - android ❌ `INTERNAL_ERROR: IntrinsicGas`
ERC20 -> AVAX trade on avalanche - android ❌ `INTERNAL_ERROR: IntrinsicGas`

ERC20 allowance approvals on optimism - android ❌ results in approval request appearing as scam in inch wallet app. This is due to the tx being sent or received on eth mainnet instead of optimism chain:
![image](https://github.com/shapeshift/web/assets/125113430/4f357c1b-179f-4e82-b61f-5fe586c1d93f)
![image](https://github.com/shapeshift/web/assets/125113430/0ed456f7-8483-4f86-bf11-73dd23cad5db)

Tested on trust wallet and seeing the same issue.
