### ISSUE TITLE
Add Mixpanel Tracking to Arbitrum Nova when turning on

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#5866]
### Overview

Currently, we arent tracking anything arbitrum nova-related on app.shapeshift.com, so adding in the appropriate tracking for mixpanel would be appreciated for helping show that its working and being used for Abritrum Grants peeps

### References and additional details

![image](https://github.com/shapeshift/web/assets/94986227/b5a7ba18-3a96-49ee-9ce3-7a20f4f74247)

![image](https://github.com/shapeshift/web/assets/94986227/af285fb1-ea69-42df-ad4c-49d2f69c263b)

Adding it to the tracking where we track the other chains

### Acceptance Criteria

Adding mix panel tracking, like we have for other chains as well.

### Need By Date

When Arbi Nova goes live and is turned on.

**Comment by gomesalexandre** [comment]
FYI @tolltalcrypto that will automagically work once the Arbitrum Nova flag is on and it is supported in swapper - this can be closed unless we want to add some new events specific to Nova?

**Comment by kaladinlight** [comment]
@tolltalcrypto turning on arbitrum nova now. as per @gomesalexandre comment, all of our standard events will be tracked accordingly (I am honestly not expecting anything to really show up for nova because there isn't really anything to do on that chain). Going to close this for now unless we determine we want something specific related to nova. Thanks!
