### ISSUE TITLE
Add Mix Panel Tracking for ThorChain Lending.

### ISSUE THREAD

**Issue by tolltalcrypto** [shapeshift/web#5917]
### Overview

Currently, we are not tracking volume on the mixpanels for lending. Adding tracking to this for data purposes and supporting the implementation and being able to track proper app.shapeshift.com volumes. 

### References and additional details

Not seeing thorchain lending in events or deposit confirmations for mixpanel.
![image](https://github.com/shapeshift/web/assets/94986227/faa5556e-1320-423a-a873-c5667652ac51)
![image](https://github.com/shapeshift/web/assets/94986227/4fb864ac-bad9-448f-875d-4bc7c315250a)

### Acceptance Criteria

Being able to track lending on app.shapeshift.com through mixpanel

**Comment by gomesalexandre** [comment]
@tolltalcrypto do we want this to be tracked under `Deposit Confirm` so we can filter for it alongside other DeFi deposits?
Asking because lending is *not* a DeFi opportunity so that wouldn't really fit into that pattern. Will go with some lending specific terminology for now, but we can always re-assess if we prefer to track under a different umbrella 🙏🏽

**Comment by tolltalcrypto** [comment]
@gomesalexandre I was just mostly referencing the deposit confirmation because I wanted to make sure I didnt miss it in there some how. 

I'd 100% support it having it's own section/tracking.
