### ISSUE TITLE
[Swapper] Inconsistent fee handling based on wallet connected

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#5962]
Different wallets (with no FOX balances) produce different fees for certain trades. 

To repro

1. connect to app.shapeshift.com with a MM / EVM style wallet 
2. Swap 5 eth for FOX, notice the SS Fee
3. 
![Screenshot 2024-01-09 at 6 21 21 AM](https://github.com/shapeshift/web/assets/15096737/6f3e18f0-3a30-4ae6-b9cb-698cccd8c447)
4. disconnect and re-connect a KK 
5. enter the same trade into swapper.
6. See that the SS fee is "free" and no fox power present to explain it.
![Screenshot 2024-01-09 at 6 22 38 AM](https://github.com/shapeshift/web/assets/15096737/f3886492-070e-42f8-8c8b-746ccfec185d)
![Screenshot 2024-01-09 at 6 22 47 AM](https://github.com/shapeshift/web/assets/15096737/a8a5d891-91cc-47c2-b14f-8974fa2bef64)

https://github.com/shapeshift/web/assets/15096737/4e5a4b93-d94f-4ba0-b7b8-889acabcf95d

**Comment by gomesalexandre** [comment]
@0xean this is expected, although with caveats, see https://github.com/shapeshift/web/issues/4518. tl;dr ZRX and 1inch swaps with EVM as a sell asset are broken with KK when donations are enabled, and should be monkey patched to no affiliate bps.

There was previously a bandaid for EVM 0x and ZRX (though, looking at https://github.com/shapeshift/web/issues/4518#issuecomment-1553859940, Li.Fi should have it as well but it doesn't - @woodenfurniture to confirm), which behavior was effectly changed by https://github.com/shapeshift/web/pull/5403

As can be seen on https://github.com/shapeshift/web/pull/4539, we previously had a `useDonationBelowMinimum` doing precisely what it implies, with swapper granularity. However, multi-hop swapper, and consequently #4539, do have a single quote input for all quotes.
This means that the swapper granularity was lost in the KK monkey patch, and we now disable affiliate fees for *all* quotes, including THOR (and Li.Fi, once again waiting on @woodenfurniture to confirm whether it should be disabled or not).

There will be a few PRs incoming:

1. Reverting the bandaid granularity so that THOR and Li.Fi are not affected by it
2. Removing the donation feature entirely and its flag to keep things simple and make debugging easier without the donation/FOX discounts branching
3. A draft PR removing the monkey patch entirely, to be opened after extensive testing and confirming with @shapeshift/operations EVM "donations" (affiliate fees) aren't affected by this bug anymore on KK

**Comment by 0xean** [comment]
Thanks @gomesalexandre for taking a look at this. I appreciate all the historical context as well.

**Comment by gomesalexandre** [comment]
Closed by https://github.com/shapeshift/web/pull/6004
