### ISSUE TITLE
Changing wallets does not refresh account info

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/web#6116]
When I change the connected wallet, say from Native to Metamask, we end up with the accounts and balances from _both_ assets.

E.g. when switching into Metamask from Native I get a second account 0, but the header account address is wrong for the newly added account (it still shows the previously connected wallet address for account 0).

![Image](https://github.com/shapeshift/web/assets/97164662/a2a5670a-826a-481d-ae82-bdb1ae4e1042)

This is super bad UX, though not critical priority because as far as I can tell there is no risk of losing funds or using the wrong account here, as a) we won't build the quotes for the non-connected wallet, and b) the user would have no ability to sign them even if we did.

**Comment by woodenfurniture** [comment]
Currently unable to trade due to this issue. Both accounts listed as account 0, the REAL account 0 is empty, whereas my funds are in account 1 (which is listed as account 0).
![image](https://github.com/shapeshift/web/assets/125113430/f46dd4e8-8873-4e89-926a-7a4f67213166)
![image](https://github.com/shapeshift/web/assets/125113430/1b63bbbc-bee0-41ee-b1d3-42dbae2ae074)
