### ISSUE TITLE
Cosmos: Staking "Get Started" flow

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#658]
**Staking Get Started Flow/modal ([Mockup](https://projects.invisionapp.com/share/WF1262ZUU2Q6#/screens/462326164))**

As a user, I want to start staking immediately or learn about staking before aping in.

1. **Step 1 ([Mockup](https://projects.invisionapp.com/share/WF1262ZUU2Q6#/screens/462326164))**
    1. Copy: 
        1. Stake your [Asset] to earn up to X% APR*
            1. X = current APR for staking
        2. Staking is the process of holding funds in a cryptocurrency wallet to support the operations of a blockchain network and, in return, holders are rewarded for their contribution.
        3. *Returns are estimated and fluctuate with market conditions.
    2. If a user clicks ‘Learn More’ they are routed to **Step 2 (About Staking Rewards)**
    3. If a user clicks ‘Start Staking’ they are routed to the **Stake/Unstake Modal**
    4. Users only see if they don’t have a balance of [Asset] staked

**Comment by gomesalexandre** [comment]
Since @DaoDev44 has already built the staking section in #894 , I think this would be the next logical step.
It will be a new component, but if I got the abstractions right, we should be able to reuse a lot of parts.
We also don't have to get the routing right the first time, we can just make all links TODOs for now.

**Comment by DaoDev44** [comment]
Sounds like a plan to me. We can discuss next steps on monday.
