### ISSUE TITLE
Thorchain LP: Add Liquidity to an existing position

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6681]
#### AC
- [figma]([https://www.figma.com/proto/hq8z2S8QwL2DciuGR8b0GR/Thorchain-LPs?node-id=1279-16715&t=9VtNEDllB1f7Anjb-0&scaling=min-zoom&content-sca](https://www.figma.com/proto/hq8z2S8QwL2DciuGR8b0GR/Thorchain-LPs?node-id=1279-16715&t=9VtNEDllB1f7Anjb-0&scaling=min-zoom&content-scaling=fixed&page-id=1279%3A12227&starting-point-node-id=1279%3A13508))
- for users already have an existing liquidity position in the same pairing that they are attempting to add to, show the existing position and make it clear they are adding vs creating a new position
- remove existing warning for non supported positions since now have this view.

**Comment by kaladinlight** [comment]
https://cdn.discordapp.com/attachments/885616186623148062/1257801350763253890/image.png?ex=6685ba4a&is=668468ca&hm=9e3a7fef7bfeb761c2432055e1c25407cf46b7be6471ce03cb21a74eaf16cb63&

**Comment by 0xean** [comment]
@reallybeard to work on some mocks

**Comment by 0xean** [comment]
https://www.figma.com/proto/hq8z2S8QwL2DciuGR8b0GR/Thorchain-LPs?node-id=1279-16715&t=9VtNEDllB1f7Anjb-0&scaling=min-zoom&content-scaling=fixed&page-id=1279%3A12227&starting-point-node-id=1279%3A13508

**Comment by 0xean** [comment]
<img width="170" alt="Screenshot 2024-07-08 at 4 18 50 PM" src="https://github.com/shapeshift/web/assets/15096737/cb719b76-111d-43e0-8770-c0627338f80f">

grey out the disabled button and add tooltip to explain that this action is not supported by TC

cc @twblack88

**Comment by twblack88** [comment]
We probably want tooltips for the new positions too (unless we already have a warning modal)

`Not supported` copy: "Due to your existing Asymmetric Rune position, depositing into this pool with both assets isn't possible. Please withdraw your current position if you wish to create a new LP with both assets."

`New Position` copy: This will create a new LP position instead of adding to the existing one.
