### ISSUE TITLE
'Amount too low' ui/ux weirdness for BTC loan repay

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6696]
### Overview

When trying to repay BTC load, if the amount is too low to repay, you cannot enter an amount to repay, it stays as $0.00 or 0 btc and you cant type in the input area

### References and additional details

https://github.com/shapeshift/web/assets/100157997/36ed231d-21c1-4138-856f-07e3f75d9cd8

### Acceptance Criteria

Should be able to enter amount to repay even if the amount is too low

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
#6697 related

**Comment by gomesalexandre** [comment]
@MBMaria that one is working as expected - the amount is not set by us as a prorate, but by the THOR response - if the amount is too low then the amount is effectively 0 as we have no response.

Not being unable to type an amount is also expected for the same reason since this is percentage-based, not amount-based, the amount is just there for reference only.

Is there any behavior that you would expect as a user here, except for the typing part?

**Comment by 0xean** [comment]
if error state, do not display value and instead show tool tip with error information
