### ISSUE TITLE
Max ETH repay saying amount to low but smaller amount are repayable

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#6697]
### Overview

When attempting a full repay on an ETH loan with a low balance, the full amount is saying "Amount to low". If i move the slider bar and choose a smaller amount it allows me to broadcast the transaction

### References and additional details

https://github.com/shapeshift/web/assets/100157997/a9e41fed-552a-43ec-a2cb-184e7f2bd1a8

### Acceptance Criteria

If can repay smaller amounts than the max loan , then should be able to repay full amount

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xean** [comment]
#6696 probably related.

**Comment by gomesalexandre** [comment]
@MBMaria this isn't a bug either - a full loan repayment warrants a collateral refund - which can't be done because the amount is too low. However, anything less than a 100% repayment is just that, a partial repayment without a refund.

What would make it clearer for you as a user here? Perhaps making a separate copy for the 100% case would help here e.g something like this?

<img width="419" alt="image" src="https://github.com/shapeshift/web/assets/17035424/99c1d426-6fad-4a02-8b35-bea6863100c9">

**Comment by 0xean** [comment]
"Amount too low to return collateral" approved language per product

**Comment by MBMaria** [comment]
Repay button is red when first trying to repay an amount. Can slide the amount bar down and then back up to full amount to get it to turn blue to allow you to repay 

https://github.com/shapeshift/web/assets/100157997/0e163fbe-1e1c-4a3c-b82d-e8313930174c
