### ISSUE TITLE
COWSwap trades "Not enough asset.chain to cover gas" 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#6891]
### Overview

Currently in production, when performing a near max balance trade of a COWSwap eligible trade pair, The app blocks the user providing a "Not enough asset.chain to cover gas"  of the outgoing asset in the trade pair.  Trades leaving ample dust are able to be performed. 

### References and additional details

https://jam.dev/c/91141bf8-26df-43bb-a264-fd80fd47d08e

Video with console log errors ^

Additionally there is a captured issue of Li.Fi having issues calcualting gas that was captured in the recreation of the trade error message.  

### Acceptance Criteria

Allow users to trade their full balances thorough COWswap if they have enough gas to perform the trade in their wallet. A user should not have to be left with dust if they would like to trade their whole balance of an asset and have the correct gas in thir address to pay for the trade.

**Comment by 0xean** [comment]
Main issue to be addressed here

Trade MAX of an ERC20 fails with cowswap

**Comment by gomesalexandre** [comment]
For reference after checking the jam: Li.Fi errors are 429s - not so much failures but rather rate limiting, trying again would make things happy, though we should obviously fix those 429s with our own Li.Fi proxy eventually. See https://docs.li.fi/rate-limits-and-api-key

**Comment by gomesalexandre** [comment]
Re: CoW, following the new fee model, the fees are *added* on top of the amount being sold. i.e if selling 200 FOX, you'd be selling 20 FOX + at most  0.03299079992581711 FOX fees bribing the solvers.

See this doc for ref:

https://docs.google.com/document/d/1w1jxRUfSbQU-15FgC-sw85pY2Ep8-VDACEwzvndylvk/edit#heading=h.mk00c6ka1y5k

Now the fee would always be quite low, and at execution time, there may *not* be a fee at all in the end.

Since close to send maxes seem to be the issue here, I believe the best way to get around this would be to simply assume no fee - and construct a payload with no fees in the case the amount is between max balance and max-balance - fee.

See this PR for reference https://github.com/shapeshift/web/pull/6455

**Comment by 0xean** [comment]
> Since close to send maxes seem to be the issue here, I believe the best way to get around this would be to simply assume no fee - and construct a payload with no fees in the case the amount is between max balance and max-balance - fee.


If we construct a payload with no fees, doesn't the order have less of a chance of being filled?  Why can we not instead construct the payload to include the fee, but just less sell amount and if the user ends up with some small dust, thats an acceptable outcome.

**Comment by 0xean** [comment]
(again, assuming the estimated fee is very low)

**Comment by gomesalexandre** [comment]
> > Since close to send maxes seem to be the issue here, I believe the best way to get around this would be to simply assume no fee - and construct a payload with no fees in the case the amount is between max balance and max-balance - fee.
> 
> If we construct a payload with no fees, doesn't the order have less of a chance of being filled? Why can we not instead construct the payload to include the fee, but just less sell amount and if the user ends up with some small dust, thats an acceptable outcome.

We absolutely could - though that's not the spec that we were told by by the CoW team @0xean. But yeah, I also believe this is the best option, removes the guesswork both for us and users (paying additional token fees is quite uncommon to say the least!)

**Comment by 0xean** [comment]
great, thanks!
