### ISSUE TITLE
Implement rFOX dashboard functionality 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6948]
https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=635-4708&t=rKiPIPofUI4duT4G-0

- leave FAQ for @twblack88 to create
- all data available / shown in UI
- For the below values, just create placeholders, (exception for the total fox staked, which we can pull from onchain)
![Screenshot 2024-05-20 at 5 38 29 PM](https://github.com/shapeshift/web/assets/15096737/953b03a8-3535-4866-805b-96ccb2f552c5)

**Comment by twblack88** [comment]
Tim to write the FAQ copy.

**Comment by twblack88** [comment]
FAQ copy. 

**What is rFOX?**
rFOX is a term used to describe the benefits and rewards you receive when you stake your FOX tokens on Arbitrum. Currently, you lock and unlock vanilla FOX (on Arbitrum) tokens for staking emissions. 

**Why stake your FOX?**
Staking your FOX allows you to earn regular RUNE payouts from the DAO's treasury, providing a steady stream of passive income in RUNE per epoch. Additionally, a portion of the RUNE received by the DAO is used to buy FOX from the open market and burn it, reducing the overall supply. Staking also supports the ShapeShift DAO's alignment with the THORChain ecosystem, contributing to their growth and success. The staking process requires a minimum 28-day unstaking period, encouraging  commitment and stability within the community.

**How do I stake my FOX?**
To stake your FOX, you use the staking interface to lock your FOX tokens into the staking contract. You will need to sign a message or transaction to assign the address where your RUNE rewards will be paid. Once staked, you start earning RUNE rewards per block as part of your staking benefits.

**What happens when I unstake?**
When you decide to unstake, there is a minimum 28-day unstaking period. During this time, your FOX remains locked, and you cease to receive RUNE emissions. After the unstaking period, you can unlock and retrieve your regular FOX tokens.

**How long is the cooldown period?**
The cooldown period for unstaking FOX tokens is 28 days. During this time, your tokens remain locked and cannot be transferred.

**Can I have multiple unstaking amounts?**
Yes, you can have multiple unstaking amounts. Each unstaking action will have its own 28-day cooldown period.

**How do total fees collected, total FOX staked, emissions pool, and FOX burn amount connect?**
The fees collected by the DAO are in native RUNE. A portion of this RUNE is distributed to FOX stakers as rewards, while another portion is used to buy FOX from the open market and burn it, reducing the overall FOX supply. The total FOX staked influences the distribution of RUNE rewards, as rewards are distributed pro-rata based on the amount of FOX staked. The emissions pool represents the amount of FOX available for staking rewards, and the FOX burn amount is the portion of FOX purchased and burned using the RUNE collected from fees.

**Comment by NeOMakinG** [comment]
Updating the FAQ right now

**Comment by 0xean** [comment]
Also please remove the "My Reward Balance"
