### ISSUE TITLE
vercel for PRs from forks

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/web#696]
we previously used vercel for preview environments (aka ephemeral) that would run on every PR from members of the shapeshift org, and could be run optionally for PRs from contributors outside the org from forks of the web repo

now that we're using cloudflare pages for production builds, the preview environments only work for members of the shapeshift github org.

as we create more bounties we are going to have more and more PRs coming from forks, and it is super valuable for engineering/operations/product to be able to test in a live preview environment

please configure vercel via a github action (not the GUI) to detect if a PR is coming from a fork and run automatically

note for @reidrankin re security - we isolated actual private environment variables to github environments in the lib repo (e.g. npm token for package publishing), so it's safe to run web preview environments from external contributors.

@cjthompson when you implement this - **please clearly communicate to operations and product that engineering should give the OK in terms of security before testing anything involving a transaction against external PRs** - it's still possible to sneak in a dependency and swap out addresses before signing a tx.

**Comment by samortaylor** [comment]
The desire to use github actions to trigger vercel builds wasn't possible due to the fact we would need to store secrets in github and secrets are not passed to github action workflows that are triggered by a pull request from a fork.

We wanted to use github actions as a way to only build preview environments on pull requests that come from forks. 

Instead we configured vercel the usual way, vercel will monitor the Web repo and trigger builds for every PR. Using a [Ignored Build Step](https://vercel.com/docs/concepts/projects/overview#ignored-build-step) we are able to identify PRs that come from forks using the following command `[ "$(git rev-parse --abbrev-ref HEAD@{upstream} | grep -o '^[^/]\+/' | sed 's%/$%%')" != "shapeshift" ]`.

During the configuration of vercel we hard-coded certain build dependencies (`shasum`), and hard-coded development environment variables. It's possible that changes in the future will break these build environments and changes will need to be made in vercel to resolve.
