### ISSUE TITLE
Arb bridge implementation for rFOX

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6978]
The [arbitrum bridge](https://bridge.arbitrum.io/?destinationChain=arbitrum-one&sourceChain=ethereum) is the primary way we expect users and dao contributors to move FOX between mainnet and arb.  It would be nice to have this intergrated into our UI both as a "swapper" and integrated into the rFOX staking flow as show in the [figma](https://www.figma.com/design/REOouo0sAuOhoD597yZEGE/rFOX?node-id=651%3A5908&t=0lE579w44KidNaCh-1)

This ticket is specifically for the rFOX implementation, but we should as much of the bridge tx logic reusable for integration into the swapper as well

Docs:

https://docs.arbitrum.io/build-decentralized-apps/token-bridging/overview
https://github.com/OffchainLabs/arbitrum-tutorials/tree/master/packages/token-deposit

@shapeshift/product will add copy for an additional warning that is displayed in the flow that alerts the user that bridging back will take 7 days and can be done using the arbitrum bridge.

**Comment by 0xean** [comment]
https://github.com/shapeshift/web/issues/6968#issuecomment-2127823078

**Comment by 0xean** [comment]
@shapeshift/product - we may want some additional messaging warning users to the delay in bridging back from L2 -> ETH. 7 days

https://docs.arbitrum.io/arbitrum-bridge/quickstart#withdraw-eth-or-erc-20-tokens-from-child-chain-to-parent-chain

cc @twblack88 / @reallybeard

**Comment by gomesalexandre** [comment]
@twblack88 / @reallybeard in addition to a warning ack of sorts, we'll also want to change the copy and UI at confirm step:

<img width="556" alt="image" src="https://github.com/shapeshift/web/assets/17035424/cb1045de-b53a-4fd7-b09c-131fbc730030">

- "Successfully received FOX on Ethereum" -> I didn't, since there's 7 days to withdraw
- `1 FOX` -> probably needs a little UI reminder that this isn't there yet and they will need to claim it in 7 days
- re: claim Tx, not sure we'll want to implement claim functionality or even claim available notification in the app (i.e we'd have to alway poll on app load, and even if we do, where would it fit in the app visually? we don't really have a list of actionable "notifications" of sorts yet) but should probably find a nice place to link them to Arbitrum Bridge UI after "swapping" so they can eventually claim there

**Comment by twblack88** [comment]
Great callouts @gomesalexandre . i think there are two options: 
- change up copy and add a warning (either modal or inline). add a link to the native bridge 
- build a unified Bridge claims route (allowing us to do more bridges down the line )

**Comment by gomesalexandre** [comment]
Definitely inclined towards option 1 @twblack88, the second option is a much bigger lift and won't really fit swapper pattern. We don't just need a route, we need to be able to poll somehow, somewhere in the app and notify users somewhere, that they have a claim ready.

Happy to discuss the notification feature we previously brought the idea of, but that's an absolute stretch here

**Comment by 0xean** [comment]
https://github.com/shapeshift/web/issues/7009
https://github.com/shapeshift/web/issues/7010

implementation tickets for this specifically into rFOX

**Comment by NeOMakinG** [comment]
Seems like it's done!
