### ISSUE TITLE
[Spike] Custom token input for swapper (asset in or out)

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#6980]
- Add the ability for a user to add a custom address + designate a chain for the swapper than can be used as the asset in or out. 
- users should be warned about the risks
- they probably need to select a chain specifically to ensure they don't get rugged by a token they don't intend to interact with, seems maybe impossible, but worth letting power users be power users. 
- how to handle non existent market data?
- error state when token not supported by 0x or lifi (trigger event so we can capture this and track it in mixpanel) 
- instrumentation to track how frequently in general this is used for swaps 
- general estimate on level of effort to implement this and communication with product on any UX concerns as they mock up the flow. 
- time box to 4-8 hours. 
- create a gist and link here or comment here as the output

**Comment by 0xApotheosis** [comment]
WIP - a stream of consciousness on the potential approach. I'll write this up more concisely tomorrow.

# UX

- Change "Search for asset" to "Search name or paste address" in the asset search box
- When a token address is searched, show the token result (including name, symbol, logo, and a block explorer link to the token) and it's supported chains
- Allow the user to "import" the token and acknowledge the risk involved in trading a custom token
- This token is added to the store and it's market data is fetched (see note on guarantee below)
- The token is then tradable via our LiFi swapper and maybe CoW (see rationale on why these swappers below)

Example import flow on 1inch:

<img width="505" alt="Screenshot 2024-06-24 at 4 30 56 PM" src="https://github.com/shapeshift/web/assets/97164662/692ec584-fe4c-44ca-bdac-5aaa4cb54804">

<img width="510" alt="Screenshot 2024-06-24 at 3 28 12 PM" src="https://github.com/shapeshift/web/assets/97164662/313bc235-53a4-47df-964a-43d2cbf4aaab">

# Upstream providers

## Getting token metadata

Requests will need to be made to get token metadata using the user inputted token address:

- Decimals
- Logo
- Name
- Symbol

We can use a debounce and token address validation to reduce unnecessary network requests.

### Alchemy as the data source

We could use Alchemy's `alchemy_getTokenMetadata` jsonrpc [method](https://docs.alchemy.com/reference/alchemy-gettokenmetadata), or the SDK, since we already have an API key and the SDK as a web dependency:

<img width="463" alt="Screenshot 2024-06-24 at 3 58 33 PM" src="https://github.com/shapeshift/web/assets/97164662/717607a9-72b4-471b-93af-8005861b3362">

Or `await alchemy.core.getTokenMetadata("0x03352d267951e96c6f7235037c5dfd2ab1466232")`

Supported chains: Ethereum, Polygon, Optimism, Arbitrum, Base.

We might want to find another provider that has more/the remaining chains?

### Chainbase as the data source

Chainbase has `https://api.chainbase.online/v1/token/metadata` which might be more appropriate at is supports more of our chains: Ethereum, Polygon, BSC, Avalanche, Arbitrum One, Optimism, Base.

## USD price data

If the custom token is valid for trading (i.e. LiFi supports it), it means that [USD price data is available via Zerion or debank](https://github.com/lifinance/customized-token-list). We have have to do an on-the-fly market data update to the store when one of these tokens is added.

We already have a Zerion API key, so ideally we can continue using this for the market data.

# Local storage

Store imported tokens in local storage such that they will persist for the user until the cache is cleared.

# Swapper support and token validation

We probably want to disallow the importing of tokens that have no supported swappers.

Of note, our token list is a superset of CoinGecko. The 0x [supported token list](https://help.0x.org/en/articles/8260697-how-to-query-which-tokens-are-available-to-be-swapped-through-0x-api) is the just the CoinGecko list, which means no imported tokens will be supported by 0x, as we _already have_ all supported 0x tokens available in the app.

That leaves LiFi and CoW as the swappers that will handle any imported tokens. If the assumptions in this section is true, we can thus use LiFi's [supported token list](https://li.quest/v1/tokens) to validate if an imported token can be traded. TODO on CoW - can we get a generated supported token list?

# Open questions

1. Do we allow the import of tokens we can't find upstream metadata for? My take is that we do not - they won't be tradeable, and so there is no value in doing so. We should instead validate them on import.
2. Can we generate a list of supported tokens for CoW Swap? If not, a naive approach could be to call CoW's `api/v1/token` endpoint to see if it knows about the token. This seems like a reasonable network cost, as we'll only be doing this one token at a time on explicit user request.

# Out of scope

This approach assumes we do not support token search by symbol or name, e.g. 1inch:

<img width="514" alt="Screenshot 2024-06-24 at 3 27 19 PM" src="https://github.com/shapeshift/web/assets/97164662/64c8fd88-9547-4408-8cbd-fb783a097edc">

**Comment by 0xean** [comment]
- add warning about importing custom tokens and risks

**Comment by 0xean** [comment]
Spike completed, next steps mocks and then implementation. LOE somewhere less than a week.
