### ISSUE TITLE
BUG: Native wallet selection

### ISSUE THREAD

**Issue by reallybeard** [shapeshift/web#6990]
### Overview

On desktop when you select a native wallet from the connect wallet modal. And then hit the back button you cannot select another wallet.

### References and additional details

Somewhere in the native wallet modal code.		

### Acceptance Criteria

User can select a native wallet, go back and select another wallet.

**Comment by 0xean** [comment]
has been attempted to be fixed before and wasn't able to be quickly resolved. Strap in :)

**Comment by NeOMakinG** [comment]
> ### Overview
> On desktop when you select a native wallet from the connect wallet modal. And then hit the back button you cannot select another wallet.
> 
> ### References and additional details
> Somewhere in the native wallet modal code.
> 
> ### Acceptance Criteria
> User can select a native wallet, go back and select another wallet.
> 
> ### Need By Date
> _No response_
> 
> ### Screenshots/Mockups
> _No response_
> 
> ### Estimated effort
> _No response_

Do you mean that you can't select `Native Wallet` again? Because I'm still able to select any other wallet than this one after clicking on back:

https://jam.dev/c/fcccf421-f247-4981-98f4-37f2e24b6c0f

Does the same with any other wallet, if you select any wallet, then come back, you can't select the `same` wallet again but any others works!

**Comment by NeOMakinG** [comment]
Reopening because it wasn't the right linked PR
