### ISSUE TITLE
Missing time estimate on thorchain streaming swaps

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7049]
![Screenshot 2024-06-03 at 5 47 40 PM](https://github.com/shapeshift/web/assets/15096737/d46719b3-1dc2-4800-a528-09e6f4be8293)

We lost the time estimates on thorchain streaming swaps, add it back

**Comment by NeOMakinG** [comment]
https://dev.thorchain.org/swap-guide/fees-and-wait-times.html#wait-times

There 5 steps to perform a THORChain swap:

```
1 - Layer1 Inbound Confirmation - assuming the inboundTx will be confirmed in the next block, it is the source blockchain block time.
2 - Observation Counting - time for 67% THORChain Nodes to observe and agree on the inboundTx.
3 - Confirmation Counting - for non-instant finality blockchains, the amount of time THORChain will wait before processing to protect against double spends and re-org attacks.
4 - Outbound Delay - dependent on size and network traffic. Large outbounds will be delayed.
5 - Layer1 Outbound Confirmation - Outbound blockchain block time.
```

Historically, the thorchain swaps time has been disabled because we were using the `total_swap_seconds` attribute of thornode response which represents an estimation of the step 3 and 4.

https://dev.thorchain.org/concepts/delays.html

In order to activate this again, we need:
- (step 1) A way to calculate the time for a next block to be validated for the starting chain
- (step 2) A way to calculate how much time will 67% of the thorchain nodes take to validate the operation (according to thorchain doc, it takes secondes to minutes, but I couldn't find a proper way to calculate this precisely)
- we already have the estimation for the step 3 and 4 (if the estimation is right)
- (step 5) Same as step 1 but for the destination chain

PLUS: 
- (step 6) If it's a swapOut, et might need to estimate the time it will take to swap to the longtail asset

**Comment by gomesalexandre** [comment]
For context - time estimation on streaming swaps has been removed in https://github.com/shapeshift/web/pull/5868/files#diff-7c6ea7dd104063ccb4b2272b34e9cbe84f738c52b106cb3597368d29e79a53d8R116-R120 - @woodenfurniture to bring more context though comment should be pretty straightforward.

We didn't have polling of latest Tx status during execution using Midgard back then, however @woodenfurniture has introduced this since then, so IMO we're fine to simply uncomment said code and have the not-so-accurate time-to-completion now that we have pretty much real-time status updates during execution

**Comment by NeOMakinG** [comment]
For context: https://discord.com/channels/554694662431178782/886041582422356018/1247999569522851840
