### ISSUE TITLE
Flakiness with max send of BTC - underquoting amount able to send 

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7084]
### Overview

The max amount is way less that what Thorswap is quoting. 
Also experiencing this error from time to time: selecting max send of BTC (or an amount close to max send) gives an error 'The request failed and the interceptors did not return an alternative response" . Sometimes this goes away other times it doesnt. 

### References and additional details

Checked Thorswap and their quote for a max send of BTC with a balance of $500 is $490 yet our site says $391 . Seems off. 
![image](https://github.com/shapeshift/web/assets/100157997/05dc2061-d1fa-4fcf-b0da-3c2dcf14754c)

https://jam.dev/c/b161e6fc-af6a-48e7-aee4-766ab16bc61a 

Selecting to send $200 out of a balance of $500 allows me to continue to the next screen and shows fees as $5.50 currently. 
![image](https://github.com/shapeshift/web/assets/100157997/58529dab-63a4-4672-bece-d0b5593eb9df)

### Acceptance Criteria

Should be able to send max amount of BTC (or close too)

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
I was able to recreate this issue with both the "Invalid address" error and the Max button firs providing an out of gas red error button and then a much smaller amount than what my current balance is: 
![Screenshot 2024-06-10 at 10 21 44 AM](https://github.com/shapeshift/web/assets/94998097/93d67db0-8a97-4448-9a69-442dc4b729de)

**Comment by gomesalexandre** [comment]
Jam repro: https://jam.dev/c/de763a78-d150-46b9-b7f5-a4e0b5e228f0

There are a few things at play here:

1. currently some shenanigans with the bitcoin unchained endpoint timing out on `/fees` which explains the very long loading time and, eventually, the long error message you've been seeing:

<img width="873" alt="image" src="https://github.com/shapeshift/web/assets/17035424/5cecad9b-4ca0-42d5-b1dc-afae0a216a53">

We sould handle this explicitly, not to surface such internal error to the user

2. I was able to repro the initial "Insufficient funds" error on max send initially popping up 

3. However as far as getting a much smaller amount, I wasn't able to repro (tested with native seed) - is this still happening? Gut feel is this was either:
 - unchained shenanigans too
 - very unlikely, but possibly a legit estimation because of the UTXO set 
 
Authored https://github.com/shapeshift/web/pull/7095 which fixes the flakiness, but doesn't tackle the un-reproducible low max amount

@MBMaria @purelycrickets ^
