### ISSUE TITLE
Contract call for dashboard stats on rFOX

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#7092]
Spike into a way to provide the contract data for users trying to find the pool data and their individual stake on rFOX.  

unblocks #6948

**Comment by woodenfurniture** [comment]
A users stake as a percentage of the total pool can be a point sample, calculated as `stakingInfo.stakingBalance / totalStaked`, but if we intend to display the expected reward for the current (or past) epoch things get a fair bit more involved because the accounting has to include staking and unstaking throughout the epoch.

The expected RUNE reward for the current epoch is calculated as `(userEpochReward / totalEpochReward) * epochDistributionAmountRune`. 

*  `userEpochReward` is easily calculated as `earned` for the end of the current epoch, minus `earned` for the end of the previous epoch.
* It appears the total reward for a given epoch is not as simple as getting the `rewardPerToken` and `totalStaked` for the end of the epoch and multiplying them, as this doesnt take into account staking interactions which occur throughout the epoch. 

Noting the performance requirement for client-side querying of the "current total epoch reward", we'd likely have to take one of the following actions:
    1. Add accounting logic to the contract to allow querying this on-chain
    2. Create an indexer to aggregate events into a db for client-side querying

**Comment by woodenfurniture** [comment]
To clarify, the amounts we need to calcuated are in the red box


![Image](https://github.com/shapeshift/web/assets/125113430/dbafede8-b5a8-4c60-89d7-7cc3636311ce)

**Comment by woodenfurniture** [comment]
Some insight which could be relevant:
https://github.com/shapeshift/rFOX/issues/58#issuecomment-2153232420

>SANITY CHECK:
>
>Does the sum of the earned rewards for the epoch match the expected amount of earned rewards (REWARD_RATE * seconds in epoch)

I true the total would simply be `REWARD_RATE * seconds in epoch`

**Comment by woodenfurniture** [comment]
Its very close to being correct, outcome here
https://github.com/shapeshift/rFOX/issues/58#issuecomment-2159630701

**Comment by woodenfurniture** [comment]
Will turn this into a ticket with pseudocode for the reward % of total, assuming we have access to the rune distribution amount which is spiked in

**Comment by woodenfurniture** [comment]
Ticketed here
https://github.com/shapeshift/web/issues/7115
