### ISSUE TITLE
Unable to deposit in LPs

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#7446]
### Overview

trying to deposit into LPs just spins/loads continuously

### References and additional details

![image](https://github.com/user-attachments/assets/e74db36f-3512-439c-a874-1301e6aee9bc)

https://jam.dev/c/2daab18f-dd49-4a48-a63e-15c223a75662

### Acceptance Criteria

Should be able to deposit into LP

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by 0xApotheosis** [comment]
I suspect the cause of this is the unpredictable gas limit:

<img width="1340" alt="Screenshot 2024-07-31 at 2 19 09 PM" src="https://github.com/user-attachments/assets/64eea10b-6d98-490a-9312-1633e666ef7e">

**Comment by MBMaria** [comment]
this is on chrome too, btw

**Comment by gomesalexandre** [comment]
Tenderly run: https://www.tdly.co/shared/simulation/195511ab-3f60-4210-b605-0bf450a7943e

This is with the same args as with the `estimate` call in the Jam, only with the `expiry` modified to a later time, as the contract call would otherwise revert as quote expired.

As can be seen above, the reason behind those `estimate` failures is allowance not yet granted... Though that would only happen for EVM chains, not DOGE as noted above and we should handle this gracefully either way (i.e fire a request either for approval Tx *or* akschual Tx) so I suspect there's something else going on here.

**Comment by kaladinlight** [comment]
Related: https://github.com/shapeshift/web/issues/7462
