### ISSUE TITLE
Audit signing flows for ledger to ensure we prompt for app opening 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7567]
See https://github.com/shapeshift/web/issues/7339 and https://github.com/shapeshift/web/issues/7374

We want to confirm that at signing times we reuse the flow from #7339 to prompt users to open the app on their ledger correctly. 

This ticket is to audit the app to find any flows we have missed and create follow up tickets for any places that need implementation

**Comment by gomesalexandre** [comment]
Currently consumed in:

- swapper's `<VerifyAddresses />`
- swapper's approval step
- Account Management's drawer
- swapper hop step

Unimplemented in:

- RFOX (captured in https://github.com/shapeshift/web/issues/7374 and WIP in https://github.com/shapeshift/web/pull/7569) - failing as `useEvmFees()` time

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/314ba516-29e5-4ee3-8967-ba75e56a0706">
<img width="776" alt="image" src="https://github.com/user-attachments/assets/eaeed110-1b10-4347-bf0a-d8258da431c5">

- LP - currently failing at signing time

<img width="1417" alt="image" src="https://github.com/user-attachments/assets/50ee190f-edb3-4cc3-af7c-ff039f1d9fc9">

- DeFi section 
  - failing at `handleContinue` approval fees estimation time for THORChain savers, as a result of `getFeesWithWallet` *actually* using wallet address derivation (same root cause as RFOX above)
  <img width="1247" alt="image" src="https://github.com/user-attachments/assets/a40b8983-4002-4a64-b4f8-452bd76f29ed">
  <img width="1267" alt="image" src="https://github.com/user-attachments/assets/97c6a6f8-f24d-4899-bbc0-5eff55310227">
  - also failing at akschual Tx time for THORChain savers deposits (no approval needed) as a result of `executeTransaction` failing in `useSendThorTx` because of `buildDepositTransaction()` failing (as expected). Same with withdraws.
  <img width="1302" alt="image" src="https://github.com/user-attachments/assets/0dc660d2-5d5d-4316-b5b8-078e78807a43">
  <img width="1092" alt="image" src="https://github.com/user-attachments/assets/42fa5522-9d60-412e-8420-a241aa5ee794">
  - UNI-V2 - failing at `getFeesWithWallet()` in `useUniV2LiquidityPool()` - same with withdraws failing at fees estimate time
  <img width="1168" alt="image" src="https://github.com/user-attachments/assets/f708a468-5fe0-4b5b-8b6a-aad2f7928d18">
  <img width="1500" alt="image" src="https://github.com/user-attachments/assets/bd6d4674-8fd3-4490-875b-99d61ebdacf9">
 - FOX farming - failing at `getApproveFees()` (approval needed) and `getDepositGasEstimateCryptoPrecision()` (approval granted) as a result of `getFeesWithWallet()` failing. Failing similarly at expired/withdraw time.
  <img width="1314" alt="image" src="https://github.com/user-attachments/assets/a0ea7714-9e21-4323-82e0-a413f948521f">
  - FOXy - failing at sign and broadcast time with `foxyApi.withdraw()` failing
  <img width="1198" alt="image" src="https://github.com/user-attachments/assets/965070b2-ce1f-45ac-9f7e-3255a9da14cf">





  
  



- Lending (note: pools are currently halted so unable to actually test this at runtime, but should be fairly sane to implement regardless)
-

**Comment by gomesalexandre** [comment]
`getFeesWithWallet()` skipping on-device derivation as a prerequisite to the *actual* Ledger gate work: https://github.com/shapeshift/web/issues/7575

More tickets to follow once re-scoped after implementing this groundwork.

**Comment by gomesalexandre** [comment]
Tickets created for:

- [DeFi section](https://github.com/shapeshift/web/issues/7579)
- [LP](https://github.com/shapeshift/web/issues/7580)

- RFOX ack is already captured in https://github.com/shapeshift/web/issues/7374
- Swapper leverages upstream gas estimations and isn't affected by the current `getFeesWithWallet()` shenanigans
