### ISSUE TITLE
Gas fee for sends of Eth on Arb seem abnormally high

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8116]
### Overview

Trying to send a small portion of eth on arb balance and getting error "Not enough Eth to cover gas". Seems like there should be enough in the account to pay for the fees but its giving an error

### References and additional details

![image](https://github.com/user-attachments/assets/f668cea7-11fd-4475-89e8-3cf19d29e198)
https://jam.dev/c/47ead148-30c6-4a30-bffe-ad795c8ba197
*recorded in release but same behaviour in prod

### Acceptance Criteria

Should be able to do sends of eth on arb

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by purelycrickets** [comment]
![Screenshot 2024-11-11 at 6 58 58 PM](https://github.com/user-attachments/assets/0b2cd338-1ed3-4560-80ac-d8bb357cc7a6)
Getting the same with a much larger balance

**Comment by NeOMakinG** [comment]
> This is probably a regression from @NeOMakinG recent changes if I had to guess. @NeOMakinG can you please take a look?
Confirmed it's not a regression from recent fixes

Took a look, it seems like `unchained` returns the same fees estimation for arbitrum one than for ethereum, as fee raised these days it's way more impacting than before, this is kinda why we just notice it now

I suggest we wait for @kaladinlight input, I don't know if the problem comes from the RPC (I don't think so), or from the oracle logic on unchained side (more likely)
