### ISSUE TITLE
Trades on Base Network failing

### ISSUE THREAD

**Issue by MBMaria** [shapeshift/web#8190]
### Overview

Attempting to trade on Base network is giving 500 server errors in console 

### References and additional details

Attempting a trade with approval 1: 
![image](https://github.com/user-attachments/assets/69ddcf5f-dd50-45c8-a3f3-4721730409bc)
https://jam.dev/c/c5279777-8c46-42a9-a24a-b87a4846ceb8
Attempting trade - the approval disappeared after the transaction finishes and the trade spits out a dud txid - also shows protocol as $2.62M . trade never completed
https://jam.dev/c/a26bb9f3-c3b2-4e5f-be0e-faf0eea0e35f

### Acceptance Criteria

Should be able to trade on base 

### Ownership

- [X] If my bounty needs engineering or needs product I have added the respective labels on the right
- [X] As the sponsor of this bounty I will review the changes in a preview environment (ops/product) or review the PR (engineering)

### Bounty Hunters

- [Join our discord](https://discord.gg/shapeshift)
- Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
- Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
- Please ***do not*** start work on this issue until you are approved in Gitcoin.

**Comment by woodenfurniture** [comment]
```
"{\"code\":-32000,\"message\":\"transaction underpriced: gas tip cap 48, minimum needed 50\"}"
```

**Comment by gomesalexandre** [comment]
Looks like BASE node is rugged (out of sync?), see copypasta from investigation in https://discord.com/channels/554694662431178782/1291232172811751485/1310820852492668968 below:

This logic works fine on other chains so assuming we respond with and/or call with wrong geth params somewhere in unchained land (48 instead of 50)

https://github.com/ethereum/go-ethereum/blob/b4d99e39176f89bb0ffbb32635e9cf17b5fd7367/core/txpool/validation.go#L120
https://github.com/ethereum/go-ethereum/blob/b4d99e39176f89bb0ffbb32635e9cf17b5fd7367/core/types/transaction.go#L343-L344
https://pkg.go.dev/github.com/ethereum/go-ethereum#CallMsg

>     GasTipCap *big.Int        // EIP-1559 tip per gas.

Ok so this guy is `maxPriorityFeePerGas` , which is 50, but *actual* tip is 48 i.e lower than the cap, this doesn't seem to be something we're in control of with Tx input
 
 Just gave a try to a ugly monkey patch to triple check the the min gas tip issue is coming from the node and us parametrizing things doesn't change anything and we get the exact same error

```diff
diff --git a/packages/chain-adapters/src/evm/base/BaseChainAdapter.ts b/packages/chain-adapters/src/evm/base/BaseChainAdapter.ts
index 5127770f95..4d3e3c6e20 100644
--- a/packages/chain-adapters/src/evm/base/BaseChainAdapter.ts
+++ b/packages/chain-adapters/src/evm/base/BaseChainAdapter.ts
@@ -83,0 +84,6 @@ export class ChainAdapter extends EvmBaseAdapter<KnownChainIds.BaseMainnet> {
+    const maxPriorityFeePerGas = fast.maxPriorityFeePerGas
+      ? BigNumber.min(48, fast.maxPriorityFeePerGas).toFixed(0)
+      : undefined
+
@@ -91 +97 @@ export class ChainAdapter extends EvmBaseAdapter<KnownChainIds.BaseMainnet> {
-        chainSpecific: { gasLimit, l1GasLimit, ...fast },
+        chainSpecific: { gasLimit, l1GasLimit, ...fast, maxPriorityFeePerGas },
@@ -99 +105 @@ export class ChainAdapter extends EvmBaseAdapter<KnownChainIds.BaseMainnet> {
-        chainSpecific: { gasLimit, l1GasLimit, ...average },
+        chainSpecific: { gasLimit, l1GasLimit, ...average, maxPriorityFeePerGas },
@@ -107 +113 @@ export class ChainAdapter extends EvmBaseAdapter<KnownChainIds.BaseMainnet> {
-        chainSpecific: { gasLimit, l1GasLimit, ...slow },
+        chainSpecific: { gasLimit, l1GasLimit, ...slow, maxPriorityFeePerGas },
```

**Comment by gomesalexandre** [comment]
@kaladinlight not sure if that helps but FYI I'm now able to broadcast BASE approval Txs, although actual Txs seem stuck in the mempool somehow https://basescan.org/tx/0xe46c5d808cf3aba3de3668f849a69371b301e62c72608b2e40dee01e62d29be7

**Comment by kaladinlight** [comment]
https://basescan.org/tx/0x4c539d408d9e7b37237d2fa9387a2f652d344d0456547cc7b88415bb75fde125
https://basescan.org/tx/0x8058860434168819d81ef363cc0dd4f8a1dbbd6be6ccea7eba75f16345b937f7
https://basescan.org/tx/0x5904e8e0cbe935d01415e85803eb0f56911e1cc8ff146cdaad950f632bb7ca00
https://basescan.org/tx/0x426118e8103775cd25ea6a0fd3eb42c2a5771b56fd8704f13bf53b03f6dcf9b2
https://basescan.org/tx/0xa00f229a578cd055ef1c3717929a18561093c9b379bbdce361b77f0cccc44ce5

Approvals and trades working. All of this is network dependent, so please keep an eye on base transaction for the next few testing cycles just to get full confidence please @shapeshift/operations, but things should be back in working order. Thanks!
