### ISSUE TITLE
Mobile app prompting users for password flow 

### ISSUE THREAD

**Issue by purelycrickets** [shapeshift/web#8257]
### Overview

Currently in Production, in the mobile app, when a user geenrates a new wallet or trys to load a wallet, ShapeShift goes through the password flow used in web.  Passwords are not set in mobile so users are faced with having to enter a password they have never set up. 

### References and additional details

wen Jam for mobile?: 
https://github.com/user-attachments/assets/75413ebc-6b4c-41cf-bbc6-dd366adb712b

password flow is prompted on initial load.  This has also been reported by a user in a support ticket. 

### Acceptance Criteria

Mobile app does not use the password flow for opening wallets.  I believe this is supposed to be set to biometrics.

**Comment by 0xApotheosis** [comment]
Progress so far:

This issue _only_ seems to appear on first load (including when switching between environments), to an environment that the user has authenticated with before.

I can reproduce the issue when pointing at any other environment other than local - for some reason this does not attempt to auto-login, and so does not dispatch `WalletActions.NATIVE_PASSWORD_OPEN`.

I can easily trigger it on a physical device (App Store build and Xcode build), but only sometimes with a simulator build (which requires typing in a password instead of FaceID), suggesting a race condition.
