### ISSUE TITLE
Lifi gas estimates are incorrect at quote time 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8271]
Lifi quotes update gas fees without showing the user which can result in unexpected fees that the user never intended to pay. 

example below - 

![Screenshot 2024-12-04 at 5 51 19 PM](https://github.com/user-attachments/assets/d0899c6c-bbd0-4666-a532-19c21f68930c)
![Screenshot 2024-12-04 at 5 51 32 PM](https://github.com/user-attachments/assets/f7138167-a878-4aa8-b3e8-55df43ff5c6e)
![Screenshot 2024-12-04 at 5 51 43 PM](https://github.com/user-attachments/assets/30e2d5fe-b622-486a-9388-5dd699d4b9d2)

**Comment by gomesalexandre** [comment]
The issue here is not in Li.Fi updating gas fees (well, it does update them but that's not the issue, more on that later) but rather estimations being totally off upstream e.g:

<img width="361" alt="Screenshot 2024-12-09 at 21 26 18" src="https://github.com/user-attachments/assets/672cd181-7825-412a-9137-216d9d3031c6">
<img width="407" alt="image" src="https://github.com/user-attachments/assets/f56d106e-8978-41c0-9461-242eff280d3a">
<img width="405" alt="image" src="https://github.com/user-attachments/assets/b608adfd-f6b1-438d-9a96-5565b0f9f9dc">

Now here is where it gets interesting: we do a final quote to Li.Fi API in :

https://github.com/shapeshift/web/blob/8d0912334fccef8548669e4f473c8cbfca94cb32/packages/swapper/src/swappers/LifiSwapper/endpoints.ts#L132

<img width="379" alt="image" src="https://github.com/user-attachments/assets/1550422c-f8c1-4304-bb28-ea0fa8cac0cd">

But it is not the culprit - in my testing, it is still extremely far from the actual gas (on the downside). I noticed however, that this guy (our own simulation from node) did have the correct networkFeeCryptoBaseUnit:

https://github.com/shapeshift/web/blob/8d0912334fccef8548669e4f473c8cbfca94cb32/packages/swapper/src/swappers/LifiSwapper/endpoints.ts#L153-L160

Unfortunately, we are limited for the time being as we cannot roll our own node simulations until an approval has been granted. We also will never be able to achieve proper estimations without a wallet connected and will always have to rely on wrong upstream ones.

Steps here:

1. Add a try/catch in Li.fi `getNetworkFeeCryptoBaseUnit` to get the fees from node if possible (there is a `from`, and approval has been granted) and default to current logic in the catch clause
2. Update network fee at quote time for Li.Fi (i.e mutate the quote, *without* actually refetching it) 

1. will be this PR, 2. TBD in https://github.com/shapeshift/web/issues/8270, porting over the logic of leveraging our own node, and showing a rate changed style modal to inform that *gas* changed (and obviously reflect it in the UI on the gas line item, too)

**Comment by gomesalexandre** [comment]
Fixed by https://github.com/shapeshift/web/pull/8313
