### ISSUE TITLE
Allow output amount to be swapped into input amount when a user attempts to reverse the input / output 

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8376]
https://jam.dev/c/f5ff458c-0ce9-4f20-94d2-54ca19368830

Repro steps:

1. create a quote 
2. click the down arrow to swap assets
3. See that it doesn't swap the assets amounts as user might expect. 

Potential solution:

 Effectively we want to take the fiat value of the current sell asset, and input that fiat amount worth of buy asset on switch.

**Comment by gomesalexandre** [comment]
@0xean what's the expected behaviour here, for the value in sell asset to become the same one in buy asset, with the assets reversed i.e something like this?
<img width="511" alt="image" src="https://github.com/user-attachments/assets/47f6703c-f0cd-4bf2-961c-2bac170750d6" />

If so, unfortunately we can't do that, as buy asset value is not an input, i.e we don't (as most of the swappers don't either) support the notion of getting a quote denominated in buy asset value.
