### ISSUE TITLE
Chainflip hangs indefinitely when attempting to sign a transaction

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#8379]
https://jam.dev/c/f2fe9c1b-42e7-44ab-98db-543223a2bd04

Repro steps:

1. connect Phantom with ledger 
2. Get a quote for SOL into USDC on SOL
3. confirm
4. attempt to sign and it never populates.

**Comment by 0xean** [comment]
I just attempted this with Rabby (ETH into SOL) and had the same experience

**Comment by Jarrel-doe** [comment]
Hello @0xean  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by gomesalexandre** [comment]
@0xean closing as this has been fixed in develop by https://github.com/shapeshift/web/pull/8309

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7530c725-d8d4-4814-bc67-e1d8585ad315" />
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/4af846aa-ae22-445d-8b86-f17c0ca9022a" />
