### ISSUE TITLE
Trade modal shows completed green check before the trade complete

### ISSUE THREAD

**Issue by SS-FOX-McCloud** [shapeshift/web#845]
The trade modal shows a green check before the trade is executed. should be a spinner until it broadcasts.

- Connect wallet to V2 (app.shapeshift.com)
- set up and submit trade
-  notice trade modal marks the trade as complete before the trade broadcasts/completes on chain

A/C:
The trade modal shows a spinner while the trade/tx is confirming.  Once trade is complete the green check should display. 

# Guidance

This is kind of tricky - we need to check the status of the most recent transaction, but we don't know when transactions are fully loaded, other than debouncing the selector on all tx ids we know about. 

Suggestion - write a selector that memoizes a debouncing incoming txid array, and runs when it changes. You may need to change the input selector, to memoize the outputted txid array. For the purposes of this UI, we can faiiirly safely make the assumption that a new tx won't come in while a trade is happening.

<img width="349" alt="Screen Shot 2022-01-10 at 2 03 03 PM" src="https://user-images.githubusercontent.com/57505863/150844498-f9c513b4-528a-4ba6-aa4b-04094e3a5e6a.png">

**Comment by 0xean** [comment]
@gomesalexandre plans to tackle this one this week, wont bounty for now

**Comment by gomesalexandre** [comment]
Had a quick fiddle on this one, and I reckon there's an easier solution, what about simply setting an un/confirmed state in `onSubmit` depending on the result / throw of `executeQuote` @SS-FOX-McCloud ? 

- set a broadcast state before calling `zrxExecuteQuote` and react accordingly on the green tick/spinner icon
- if it throws, set an error state and error icon

Since we just want to react on broadcasted tx (doesn't matter if confirmed or not), I think that's a cleaner and more reliable solution.

**Comment by 0xdef1cafe** [comment]
root cause is here https://github.com/shapeshift/web/issues/706

**Comment by 0xdef1cafe** [comment]
https://github.com/shapeshift/web/pull/1179 this might be helpful if you want to take a look at a later date @gomesalexandre

**Comment by 0xean** [comment]
@stackedq - are you interested in picking this one up? will get a bounty posted if you are!

**Comment by stackedq** [comment]
> @stackedq - are you interested in picking this one up? will get a bounty posted if you are!  

Definitely!
